@file:Suppress("unused")

package com.shifthackz.catppuccin.palette

import androidx.compose.ui.graphics.Color

object Catppuccin {

    object Latte : CatppuccinPalette {
        override val Rosewater: Color = Color(0xffdc8a78)
        override val Flamingo: Color = Color(0xffdd7878)
        override val Pink: Color = Color(0xffea76cb)
        override val Mauve: Color = Color(0xff8839ef)
        override val Red: Color = Color(0xffd20f39)
        override val Maroon: Color = Color(0xffe64553)
        override val Peach: Color = Color(0xfffe640b)
        override val Yellow: Color = Color(0xffdf8e1d)
        override val Green: Color = Color(0xff40a02b)
        override val Teal: Color = Color(0xff179299)
        override val Sky: Color = Color(0xff04a5e5)
        override val Sapphire: Color = Color(0xff209fb5)
        override val Blue: Color = Color(0xff1e66f5)
        override val Lavender: Color = Color(0xff7287fd)
        override val Text: Color = Color(0xff4c4f69)
        override val Subtext1: Color = Color(0xff5c5f77)
        override val Subtext0: Color = Color(0xff6c6f85)
        override val Overlay2: Color = Color(0xff7c7f93)
        override val Overlay1: Color = Color(0xff8c8fa1)
        override val Overlay0: Color = Color(0xff9ca0b0)
        override val Surface2: Color = Color(0xffacb0be)
        override val Surface1: Color = Color(0xffbcc0cc)
        override val Surface0: Color = Color(0xffccd0da)
        override val Base: Color = Color(0xffeff1f5)
        override val Mantle: Color = Color(0xffe6e9ef)
        override val Crust: Color = Color(0xffdce0e8)
    }

    object Frappe : CatppuccinPalette {
        override val Rosewater: Color = Color(0xfff2d5cf)
        override val Flamingo: Color = Color(0xffeebebe)
        override val Pink: Color = Color(0xfff4b8e4)
        override val Mauve: Color = Color(0xffca9ee6)
        override val Red: Color = Color(0xffe78284)
        override val Maroon: Color = Color(0xffea999c)
        override val Peach: Color = Color(0xffef9f76)
        override val Yellow: Color = Color(0xffe5c890)
        override val Green: Color = Color(0xffa6d189)
        override val Teal: Color = Color(0xff81c8be)
        override val Sky: Color = Color(0xff99d1db)
        override val Sapphire: Color = Color(0xff85c1dc)
        override val Blue: Color = Color(0xff8caaee)
        override val Lavender: Color = Color(0xffbabbf1)
        override val Text: Color = Color(0xffc6d0f5)
        override val Subtext1: Color = Color(0xffb5bfe2)
        override val Subtext0: Color = Color(0xffa5adce)
        override val Overlay2: Color = Color(0xff949cbb)
        override val Overlay1: Color = Color(0xff838ba7)
        override val Overlay0: Color = Color(0xff737994)
        override val Surface2: Color = Color(0xff626880)
        override val Surface1: Color = Color(0xff51576d)
        override val Surface0: Color = Color(0xff414559)
        override val Base: Color = Color(0xff303446)
        override val Mantle: Color = Color(0xff292c3c)
        override val Crust: Color = Color(0xff232634)
    }

    object Macchiato : CatppuccinPalette {
        override val Rosewater: Color = Color(0xfff4dbd6)
        override val Flamingo: Color = Color(0xfff0c6c6)
        override val Pink: Color = Color(0xfff5bde6)
        override val Mauve: Color = Color(0xffc6a0f6)
        override val Red: Color = Color(0xffed8796)
        override val Maroon: Color = Color(0xffee99a0)
        override val Peach: Color = Color(0xfff5a97f)
        override val Yellow: Color = Color(0xffeed49f)
        override val Green: Color = Color(0xffa6da95)
        override val Teal: Color = Color(0xff8bd5ca)
        override val Sky: Color = Color(0xff91d7e3)
        override val Sapphire: Color = Color(0xff7dc4e4)
        override val Blue: Color = Color(0xff8aadf4)
        override val Lavender: Color = Color(0xffb7bdf8)
        override val Text: Color = Color(0xffcad3f5)
        override val Subtext1: Color = Color(0xffb8c0e0)
        override val Subtext0: Color = Color(0xffa5adcb)
        override val Overlay2: Color = Color(0xff939ab7)
        override val Overlay1: Color = Color(0xff8087a2)
        override val Overlay0: Color = Color(0xff6e738d)
        override val Surface2: Color = Color(0xff5b6078)
        override val Surface1: Color = Color(0xff494d64)
        override val Surface0: Color = Color(0xff363a4f)
        override val Base: Color = Color(0xff24273a)
        override val Mantle: Color = Color(0xff1e2030)
        override val Crust: Color = Color(0xff181926)
    }

    object Mocha : CatppuccinPalette {
        override val Rosewater: Color = Color(0xfff5e0dc)
        override val Flamingo: Color = Color(0xfff2cdcd)
        override val Pink: Color = Color(0xfff5c2e7)
        override val Mauve: Color = Color(0xffcba6f7)
        override val Red: Color = Color(0xfff38ba8)
        override val Maroon: Color = Color(0xffeba0ac)
        override val Peach: Color = Color(0xfffab387)
        override val Yellow: Color = Color(0xfff9e2af)
        override val Green: Color = Color(0xffa6e3a1)
        override val Teal: Color = Color(0xff94e2d5)
        override val Sky: Color = Color(0xff89dceb)
        override val Sapphire: Color = Color(0xff74c7ec)
        override val Blue: Color = Color(0xff89b4fa)
        override val Lavender: Color = Color(0xffb4befe)
        override val Text: Color = Color(0xffcdd6f4)
        override val Subtext1: Color = Color(0xffbac2de)
        override val Subtext0: Color = Color(0xffa6adc8)
        override val Overlay2: Color = Color(0xff9399b2)
        override val Overlay1: Color = Color(0xff7f849c)
        override val Overlay0: Color = Color(0xff6c7086)
        override val Surface2: Color = Color(0xff585b70)
        override val Surface1: Color = Color(0xff45475a)
        override val Surface0: Color = Color(0xff313244)
        override val Base: Color = Color(0xff1e1e2e)
        override val Mantle: Color = Color(0xff181825)
        override val Crust: Color = Color(0xff11111b)
    }

    fun values(): List<CatppuccinPalette> = listOf(
        Latte,
        Frappe,
        Macchiato,
        Mocha,
    )
}
